#!/usr/bin/env python3
import argparse
from pathlib import Path

# Function to delete temporary files
def del_temp_files(list_of_temp_files):
    for filename in list_of_temp_files:
        print(f"Attempting to delete: {filename}")  # Debugging statement
        file_path = Path(filename)  # Use pathlib for file handling
        try:
            if file_path.exists() and file_path.is_file():  # Check if it's a file, not a directory
                file_path.unlink()  # Delete the file
                print(f"Deleted: {filename}")
            elif file_path.is_dir():
                print(f"Skipping directory: {filename}")
            else:
                print(f"File not found: {filename}")
        except Exception as e:
            print(f"Error deleting {filename}: {e}")

# Argument parser
parser = argparse.ArgumentParser(description="Delete temporary files generated by netMHC")
parser.add_argument("--rmfile", type=str, nargs="+", help="List of file paths to be deleted")  # Fixed typo
args = parser.parse_args()

# Call the function to delete files
del_temp_files(args.rmfile)


